#!/bin/bash

# This script will destroy our basic lamp stack testing environment. 
# To build, use lamp-stack--build. See below for more information. 

DATE=`date +%x`
DAY=$(date '+DATE: %m/%d/%y%tTIME:%H:%M:%S')
LAB='LAMP stack lab destoy'
NC='\033[0m' # No Color
green='\033[0;32m'
red='\033[0;31m'

# This script must be ran as root, check to see if UID matches 0.
	if [ "$(id -u)" != "0" ]; then
   		echo "This script must be run as root" 1>&2
   		exit 1
	fi


# Can we write the output to standard log file? Does it exist? $file will be used
# throughout this script, see below for the defined variable. 
	file='/var/log/lab-environment.log'

	( [ -e "$file" ] || touch "$file" ) && [ ! -w "$file" ] && echo cannot write to $file && exit 1
	echo -e "${red}$LAB started on $DAY...${NC}" >> $file


# Remove apache2 or httpd depending on operating system. 
	if python -mplatform | grep -iq Ubuntu && apt-get remove --purge mysql php apache2 -y | tee -a $file || yum remove mysql mariadb php httpd -y | tee -a $file ; then
		echo -e "${green}LAMP stack successfully removed.${NC}"
	else
		echo -e "${red}Packages failed to be removed. Please check package-manger's log and try again.${NC}"
	fi
